#!/bin/env bash
cd source
echo compile and link...
cc -c *.c
compile_result=$?
cc -o fw *.o
link_result=$?
cd ..

# install file is not present by default due to different system configuration
# below you can get a clear idea what it usually does (author is on Fedora 25)

if [ -e "./install" ] && [ $compile_result==0 ] && [ $link_result==0 ]; then
  echo copying resulting binary to ~/.local/bin
  ./install
fi
